# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#about-the-dependabotyml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    target-branch: "master"
    reviewers:
      - "damingerdai"
    labels:
      - "go"
      - "dependencies"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    target-branch: "master"
    reviewers:
      - "damingerdai"
    labels:
      - "web"
      - "nextjs"
      - "dependencies"
    open-pull-requests-limit: 10