version: "3"
services:
  pg:
    image: postgres:15
    container_name: pg
    ports:
      - 5432:5432
    volumes:
      - daming-health-master-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    networks:
      - daming-health-master-network
  pgbouncer:
    # image: edoburu/pgbouncer:1.9.0
    image: rmccaffrey/pgbouncer:1.18.1
    container_name: pgbouncer
    environment:
       - DB_USER=postgres
       - DB_PASSWORD=123456
       - DB_HOST=pg
       - DB_NAME=postgres
       - POOL_MODE=session
       - ADMIN_USERS=postgres
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    networks:
      - daming-health-master-network
    ports:
      - 6432:6432
    depends_on:
      - pg
  redis:
    image: redis:6.2.1-alpine
    container_name: 'redis'
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - daming-health-master-redis-volume:/data/redis
    networks:
      - daming-health-master-network
volumes:
  daming-health-master-volume:
    external: true
  daming-health-master-redis-volume:
    external: true
networks:
  daming-health-master-network:
    external: false
  
