version: "3"
services:
  pg:
    image: postgres:15
    container_name: 'health-master-pg'
    ports:
      - 5432:5432
    volumes:
      - daming-health-master-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      TZ: 'GMT+8'
      PGTZ: 'GMT+8'
    networks:
      - daming-health-master-network
  pgbouncer:
    image: edoburu/pgbouncer:1.21.0-p1
    container_name: pgbouncer
    environment:
      - DATABASE_URL=postgres://postgres:123456@pg:5432/postgres
      - POOL_MODE=session 
      - MAX_DB_CONNECTIONS=100
      - DEFAULT_POOL_SIZE=40
      - AUTH_TYPE=scram-sha-256
    # volumes:
      # - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      # - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    networks:
      - daming-health-master-network
    ports:
      - 6543:5432
    depends_on:
      - pg
  redis:
    image: redis:7.0.11-alpine3.17
    container_name: 'health-master-redis'
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - daming-health-master-redis-volume:/data/redis
    networks:
      - daming-health-master-network
  kuma:
    image: louislam/uptime-kuma:1.23.3-alpine
    restart: unless-stopped
    ports:
      - '3001:3001'
    volumes:
      - daming-health-master-kuma-volume:/app/data
    container_name: uptime-kuma
    networks:
      - daming-health-master-network
volumes:
  daming-health-master-volume:
    external: true
  daming-health-master-redis-volume:
    external: true
  daming-health-master-kuma-volume:
    external: true
networks:
  daming-health-master-network:
    external: false
  
