version: "3"
services:
  pg:
    image: postgres:14
    container_name: health-master-pg
    ports:
      - 5432:5432
    volumes:
      - daming-health-master-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: health-master
    networks:
      - daming-health-master-network
volumes:
  daming-health-master-volume:
    external: true
networks:
  daming-health-master-network:
    external: false
  
