version: "3"
services:
  pg:
    image: postgres:15
    container_name: pg
    ports:
      - 5432:5432
    volumes:
      - daming-health-master-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    networks:
      - daming-health-master-network
  redis:
    image: redis:6.2.1-alpine
    container_name: 'redis'
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - daming-health-master-redis-volume:/data/redis
    networks:
      - daming-health-master-network
volumes:
  daming-health-master-volume:
    external: true
  daming-health-master-redis-volume:
    external: true
networks:
  daming-health-master-network:
    external: false
  
