services:
  postgres:
    image: postgres:18.4-alpine3.24
    container_name: "health-master-pg"
    volumes:
      - daming-health-master-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      TZ: "GMT+8"
      PGTZ: "GMT+8"
    networks:
      - daming-health-master-network
    restart: always
  pgbouncer:
    image: edoburu/pgbouncer:v1.25.1-p0
    container_name: health-master-pgbouncer
    environment:
      - DATABASE_URL=postgres://postgres:123456@postgres:5432/postgres
      - POOL_MODE=session
      - MAX_DB_CONNECTIONS=100
      - DEFAULT_POOL_SIZE=40
      - AUTH_TYPE=scram-sha-256
    networks:
      - daming-health-master-network
    ports:
      - 16543:5432
    depends_on:
      - postgres
  redis:
    image: redis:8.8.0-alpine3.23
    container_name: "health-master-redis"
    command: redis-server --appendonly yes --requirepass 123456
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - daming-health-master-redis-volume:/data/redis
    networks:
      - daming-health-master-network
  kuma:
    image: louislam/uptime-kuma:2.3.2-slim
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - daming-health-master-kuma-volume:/app/data
    container_name: uptime-kuma
    networks:
      - daming-health-master-network
  pg-backup:
    image: prodrigestivill/postgres-backup-local:18
    container_name: pg-backup
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
      - BACKUP_NUM_KEEP=7              
      - BACKUP_FREQUENCY=1d            
      - TZ=GMT+8
    volumes:
      - ./backups:/backups             
    networks:
      - daming-health-master-network
    depends_on:
      - postgres
    restart: always

volumes:
  daming-health-master-volume:
    external: true
  daming-health-master-redis-volume:
    external: true
  daming-health-master-kuma-volume:
    external: true
networks:
  daming-health-master-network:
    external: false
