services:
  postgres:
    image: postgres:18.6-alpine3.24
    container_name: "health-master-pg"
    volumes:
      - daming-health-master-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      TZ: "GMT+8"
      PGTZ: "GMT+8"
    networks:
      - daming-health-master-network
    restart: always
  pgbouncer:
    image: edoburu/pgbouncer:v1.25.2-p0
    container_name: health-master-pgbouncer
    environment:
      - DATABASE_URL=postgres://postgres:123456@postgres:5432/postgres
      - POOL_MODE=session
      - MAX_DB_CONNECTIONS=100
      - DEFAULT_POOL_SIZE=40
      - AUTH_TYPE=scram-sha-256
    networks:
      - daming-health-master-network
    ports:
      - 16543:5432
    depends_on:
      - postgres
  redis:
    image: redis:8.10.1-alpine3.23
    container_name: "health-master-redis"
    command: redis-server --appendonly yes --requirepass 123456
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - daming-health-master-redis-volume:/data/redis
    networks:
      - daming-health-master-network
  kuma:
    image: louislam/uptime-kuma:2.5.5-slim
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - daming-health-master-kuma-volume:/app/data
    container_name: uptime-kuma
    networks:
      - daming-health-master-network
  pg-backup:
    image: prodrigestivill/postgres-backup-local:18
    container_name: pg-backup
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
      - BACKUP_NUM_KEEP=7              
      - BACKUP_FREQUENCY=1d            
      - TZ=GMT+8
    volumes:
      - ./backups:/backups             
    networks:
      - daming-health-master-network
    depends_on:
      - postgres
    restart: always
  mailpit:
    image: axllent/mailpit:v1.31.1
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - daming-health-master-mailpit-volume:/data
    ports:
      - "18025:8025"
      - "11025:1025"
    environment:
      TZ: Asia/Shanghai
      MP_MAX_MESSAGES: "5000"
      MP_DATABASE: /data/mailpit.db
      MP_UI_AUTH: "admin:12345"
      MP_SMTP_AUTH: "admin:12345"
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
  jaeger:
    image: jaegertracing/jaeger:2.21.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
volumes:
  daming-health-master-volume:
    external: true
  daming-health-master-redis-volume:
    external: true
  daming-health-master-kuma-volume:
    external: true
  daming-health-master-mailpit-volume:
    external: true
networks:
  daming-health-master-network:
    external: false
