apiVersion: v1
kind: Service
metadata:
  name: pgweb
  namespace: health-master-namespace
spec:
  selector:
    app: pgweb
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
   