apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: health-master-namespace
  labels:
    app: postgres
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: '123456'
  POSTGRES_DB: postgres
  TZ: 'GMT+8'
  PGTZ: 'GMT+8'
