apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  namespace: health-master-namespace
  # labels:
  #   type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
