apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: health-master-api-hpa
  labels:
    app: health-master-api

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-master-api

  minReplicas: 1
  maxReplicas: 2

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50