apiVersion: v1
kind: Service
metadata:
  name: health-master-api
  labels:
    app: health-master-api

spec:
  type: ClusterIP

  selector:
    app: health-master-api

  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP