Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60s
  WriteTimeout: 60s
Database:
  Host: 127.0.0.1
  Port: 6432
  User: postgres
  Password: 123456
  DB: postgres
  SSL: false
JWT:
  Secret: damingerdai
  Issuer: health-master
  Expire: 7200s
Redis:
  Host: 127.0.0.1
  Port: 6379
  Password: 12345
  DB: 0
Logger:
  Level: info
