apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: proxya-api-hpa
  namespace: health-master-namespace
  labels:
    app: health-master-api-hpa
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-master-api
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
