'use client';
import * as React from 'react';
import * as MenuPrimitive from '@base-ui/react/menu';
import { Separator as SeparatorPrimitive } from '@base-ui/react/separator';
import { CheckIcon, ChevronRightIcon, CircleIcon } from 'lucide-react';
import { cn } from '@/lib/utils';
const Menu = MenuPrimitive.Menu;
function DropdownMenu(props: React.ComponentProps<typeof Menu.Root>) { return <Menu.Root data-slot="dropdown-menu" {...props} />; }
function DropdownMenuPortal(props: React.ComponentProps<typeof Menu.Portal>) { return <Menu.Portal data-slot="dropdown-menu-portal" {...props} />; }
function DropdownMenuTrigger({ asChild, children, ...props }: React.ComponentProps<typeof Menu.Trigger> & { asChild?: boolean }) { return <Menu.Trigger data-slot="dropdown-menu-trigger" render={asChild ? children as React.ReactElement : undefined} {...props} />; }
function DropdownMenuContent({ className, side, align, sideOffset = 4, ...props }: React.ComponentProps<typeof Menu.Popup> & { side?: 'top' | 'right' | 'bottom' | 'left'; align?: 'start' | 'center' | 'end'; sideOffset?: number }) { return <Menu.Portal><Menu.Positioner side={side} align={align} sideOffset={sideOffset} className="isolate z-50 outline-none"><Menu.Popup data-slot="dropdown-menu-content" className={cn('bg-popover text-popover-foreground data-starting-style:opacity-0 data-ending-style:opacity-0 z-50 max-h-(--available-height) min-w-[8rem] origin-(--transform-origin) overflow-x-hidden overflow-y-auto rounded-md border p-1 shadow-md outline-none transition', className)} {...props} /></Menu.Positioner></Menu.Portal>; }
function DropdownMenuGroup(props: React.ComponentProps<typeof Menu.Group>) { return <Menu.Group data-slot="dropdown-menu-group" {...props} />; }
function DropdownMenuItem({ className, inset, variant = 'default', asChild, children, ...props }: React.ComponentProps<typeof Menu.Item> & { inset?: boolean; variant?: 'default' | 'destructive'; asChild?: boolean }) { return <Menu.Item data-slot="dropdown-menu-item" data-inset={inset} data-variant={variant} render={asChild ? children as React.ReactElement : undefined} className={cn('focus:bg-accent focus:text-accent-foreground relative flex cursor-default items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50 data-[inset]:pl-8', className)} {...props}>{asChild ? null : children}</Menu.Item>; }
function DropdownMenuCheckboxItem({ className, children, checked, ...props }: React.ComponentProps<typeof Menu.CheckboxItem>) { return <Menu.CheckboxItem data-slot="dropdown-menu-checkbox-item" checked={checked} className={cn('focus:bg-accent focus:text-accent-foreground relative flex cursor-default items-center gap-2 rounded-sm py-1.5 pr-2 pl-8 text-sm outline-hidden select-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50', className)} {...props}><span className="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center"><Menu.CheckboxItemIndicator><CheckIcon className="size-4" /></Menu.CheckboxItemIndicator></span>{children}</Menu.CheckboxItem>; }
function DropdownMenuRadioGroup(props: React.ComponentProps<typeof Menu.RadioGroup>) { return <Menu.RadioGroup data-slot="dropdown-menu-radio-group" {...props} />; }
function DropdownMenuRadioItem({ className, children, ...props }: React.ComponentProps<typeof Menu.RadioItem>) { return <Menu.RadioItem data-slot="dropdown-menu-radio-item" className={cn('focus:bg-accent focus:text-accent-foreground relative flex cursor-default items-center gap-2 rounded-sm py-1.5 pr-2 pl-8 text-sm outline-hidden select-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50', className)} {...props}><span className="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center"><Menu.RadioItemIndicator><CircleIcon className="size-2 fill-current" /></Menu.RadioItemIndicator></span>{children}</Menu.RadioItem>; }
function DropdownMenuLabel({ className, inset, ...props }: React.ComponentProps<typeof Menu.GroupLabel> & { inset?: boolean }) { return <Menu.GroupLabel data-slot="dropdown-menu-label" data-inset={inset} className={cn('px-2 py-1.5 text-sm font-medium data-[inset]:pl-8', className)} {...props} />; }
function DropdownMenuSeparator({ className, ...props }: React.ComponentProps<typeof SeparatorPrimitive>) { return <SeparatorPrimitive data-slot="dropdown-menu-separator" className={cn('bg-border -mx-1 my-1 h-px', className)} {...props} />; }
function DropdownMenuShortcut({ className, ...props }: React.ComponentProps<'span'>) { return <span data-slot="dropdown-menu-shortcut" className={cn('text-muted-foreground ml-auto text-xs tracking-widest', className)} {...props} />; }
function DropdownMenuSub(props: React.ComponentProps<typeof Menu.SubmenuRoot>) { return <Menu.SubmenuRoot data-slot="dropdown-menu-sub" {...props} />; }
function DropdownMenuSubTrigger({ className, inset, children, ...props }: React.ComponentProps<typeof Menu.SubmenuTrigger> & { inset?: boolean }) { return <Menu.SubmenuTrigger data-slot="dropdown-menu-sub-trigger" data-inset={inset} className={cn('focus:bg-accent focus:text-accent-foreground data-popup-open:bg-accent data-popup-open:text-accent-foreground flex cursor-default items-center rounded-sm px-2 py-1.5 text-sm outline-hidden select-none data-[inset]:pl-8', className)} {...props}>{children}<ChevronRightIcon className="ml-auto size-4" /></Menu.SubmenuTrigger>; }
function DropdownMenuSubContent({ className, ...props }: React.ComponentProps<typeof Menu.Popup>) { return <Menu.Popup data-slot="dropdown-menu-sub-content" className={cn('bg-popover text-popover-foreground data-starting-style:opacity-0 data-ending-style:opacity-0 z-50 min-w-[8rem] origin-(--transform-origin) overflow-hidden rounded-md border p-1 shadow-lg', className)} {...props} />; }
export { DropdownMenu, DropdownMenuPortal, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuGroup, DropdownMenuLabel, DropdownMenuItem, DropdownMenuCheckboxItem, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubTrigger, DropdownMenuSubContent };
