"use client";

import { useState } from "react";
import { ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/components/ui/card";

import { Button } from "@/components/ui/button";

import {
    InputOTP,
    InputOTPGroup,
    InputOTPSlot,
} from "@/components/ui/input-otp";


export default function Page() {
    const router = useRouter();

    const [code, setCode] = useState("");
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");

    async function handleVerify() {
        if (code.length !== 6) return;

        try {
            setLoading(true);
            setError("");

            // TODO:
            // const challengeToken = sessionStorage.getItem("challenge");
            //
            // const res = await httpClient.verify2FA({
            //   challengeToken,
            //   code,
            // });
            //
            // await signIn("credentials", {
            //   redirect: false,
            //   accessToken: res.token.accessToken,
            // });

            router.push("/dashboard");
        } catch (err) {
            setError("Invalid verification code.");
            setCode("");
        } finally {
            setLoading(false);
        }
    }

    return (

        <Card className="w-full max-w-md shadow-lg">
            <CardHeader className="space-y-4 text-center">
                <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-primary/10">
                    <ShieldCheck className="h-7 w-7 text-primary" />
                </div>

                <div className="space-y-2">
                    <CardTitle className="text-2xl">
                        Two-Factor Authentication
                    </CardTitle>

                    <CardDescription className="text-sm leading-6">
                        Enter the 6-digit verification code generated by your
                        Google Authenticator app.
                    </CardDescription>
                </div>
            </CardHeader>

            <CardContent className="space-y-6">
                <div className="flex justify-center">
                    <InputOTP
                        maxLength={6}
                        value={code}
                        onChange={(value) => {
                            setCode(value);
                            if (error) setError("");
                        }}
                    >
                        <InputOTPGroup>
                            <InputOTPSlot index={0} />
                            <InputOTPSlot index={1} />
                            <InputOTPSlot index={2} />
                            <InputOTPSlot index={3} />
                            <InputOTPSlot index={4} />
                            <InputOTPSlot index={5} />
                        </InputOTPGroup>
                    </InputOTP>
                </div>

                {error && (
                    <p className="text-center text-sm text-destructive">
                        {error}
                    </p>
                )}

                <Button
                    className="w-full"
                    disabled={loading || code.length !== 6}
                    onClick={handleVerify}
                >
                    {loading ? "Verifying..." : "Verify Code"}
                </Button>

                <Button
                    variant="ghost"
                    className="w-full"
                    onClick={() => router.push("/sign-in")}
                >
                    Back to Sign In
                </Button>
            </CardContent>
        </Card>

    );
}