apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: health-master-namespace
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    app: postgres
