name: damingerdai health health deploy

on:
  push:
    branches:
      - main
env:
  REGISTRY_NAME: github.com

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build docker
        id: build-docker
        run: |-
          docker build . -t ${{ env.REGISTRY_NAME }}/damingerdai/health-master:${{ github.sha }} -f github.Dockerfile
      - name: Image digest
        run: echo ${{ steps.build-docker.outputs.digest }}
      - name: Save docker image to tar file
        run: docker save ${{ env.REGISTRY_NAME }}/damingerdai/health-master-web:${{ github.sha }} -o header-master.tar
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: health-master.tar
          target: ${{ secrets.SERVER_TARGET_FOLDER_PATHs }}
      - name: deploy by ssh
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          sripts: |-
            cd /root/health-master; \
            docker load -o health-master.tar; \
            kubectl set image deployment/health-master-api health-master=${{ env.REGISTRY_NAME }}/damingerdai/health-master-web:${{ github.sha }} -n health-master-namespace \
            kubectl rollout status deployment/health-master-api -n health-master-namespace
            

            
